# practica 1
texto = "controlar la complejidad es la esencia de la programación"
primera_palabra = texto[:9]
print(primera_palabra)

# practica 2
texto = "Nunca confíes en un ordenador que no puedas lanzar por una ventana"
resultado = texto[8::3]
print(resultado)

# practica 3
texto = "Es genial trabajar con ordenadores. No discuten, lo recuerdan todo y no se deben tu cerveza"
resultado = texto[::-1]
print(resultado)
